In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
import os 
print(os.listdir('.'))

['requirements.txt', '.gitignore', '.venv', '.git', 'data', 'hydroponics.ipynb']

In [3]:
file_path = "data/IoTData --Raw--.csv"
if os.path.exists(file_path):
  df = pd.read_csv(file_path)
  print(df.head())
  print(df.info())

   id            timestamp   pH    TDS  water_level  DHT_temp  DHT_humidity  \
0   1  2023-11-26 10:57:52  7.0  500.0            0      25.5          60.0
1   2  2023-11-26 10:58:37  7.0  500.0            0      25.5          60.0
2   3  2023-11-26 11:01:34  7.0  500.0            3      25.5          60.0
3   4  2023-12-05 11:30:58  7.0  500.0            3      25.5          60.0
4   5  2023-12-05 11:33:50  7.0  500.0            3      25.5          60.0

   water_temp pH_reducer add_water nutrients_adder humidifier ex_fan
0        20.0         ON       NaN             OFF        OFF     ON
1        20.0         ON       NaN             OFF        OFF    OFF
2        20.0         ON       NaN             OFF        OFF    OFF
3        20.0         ON       NaN             OFF        OFF    OFF
4        20.0         ON        ON             OFF        OFF    OFF
<class 'pandas.DataFrame'>
RangeIndex: 50570 entries, 0 to 50569
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               50570 non-null  int64
 1   timestamp        50570 non-null  str
 2   pH               50570 non-null  float64
 3   TDS              50570 non-null  float64
 4   water_level      50570 non-null  int64
 5   DHT_temp         50570 non-null  float64
 6   DHT_humidity     50570 non-null  float64
 7   water_temp       50570 non-null  float64
 8   pH_reducer       50570 non-null  str
 9   add_water        50566 non-null  str
 10  nutrients_adder  50570 non-null  str
 11  humidifier       50570 non-null  str
 12  ex_fan           50570 non-null  str
dtypes: float64(5), int64(2), str(6)
memory usage: 5.0 MB
None

In [4]:
original_dataset = pd.read_csv("data/IoTData --Raw--.csv")
df = original_dataset.copy()

In [5]:
df.head()

,id,timestamp,pH,TDS,water_level,DHT_temp,DHT_humidity,water_temp,pH_reducer,add_water,nutrients_adder,humidifier,ex_fan
0,1,2023-11-26 10:57:52,7.0,500.0,0,25.5,60.0,20.0,ON,NaN,OFF,OFF,ON
1,2,2023-11-26 10:58:37,7.0,500.0,0,25.5,60.0,20.0,ON,NaN,OFF,OFF,OFF
2,3,2023-11-26 11:01:34,7.0,500.0,3,25.5,60.0,20.0,ON,NaN,OFF,OFF,OFF
3,4,2023-12-05 11:30:58,7.0,500.0,3,25.5,60.0,20.0,ON,NaN,OFF,OFF,OFF
4,5,2023-12-05 11:33:50,7.0,500.0,3,25.5,60.0,20.0,ON,ON,OFF,OFF,OFF

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50570 entries, 0 to 50569
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               50570 non-null  int64
 1   timestamp        50570 non-null  str
 2   pH               50570 non-null  float64
 3   TDS              50570 non-null  float64
 4   water_level      50570 non-null  int64
 5   DHT_temp         50570 non-null  float64
 6   DHT_humidity     50570 non-null  float64
 7   water_temp       50570 non-null  float64
 8   pH_reducer       50570 non-null  str
 9   add_water        50566 non-null  str
 10  nutrients_adder  50570 non-null  str
 11  humidifier       50570 non-null  str
 12  ex_fan           50570 non-null  str
dtypes: float64(5), int64(2), str(6)
memory usage: 5.0 MB

In [9]:
df.describe(include='number')

,id,pH,TDS,water_level,DHT_temp,DHT_humidity,water_temp
count,50570.000000,50570.000000,50570.000000,50570.000000,50570.000000,50570.000000,50570.000000
mean,25285.500000,6.001514,1154.134377,1.258829,24.316781,71.714188,21.494904
std,14598.445893,0.553016,247.507196,0.479218,1.209319,25.956493,2.174898
min,1.000000,0.270000,-283.910000,0.000000,12.300000,25.000000,0.000000
25%,12643.250000,5.630000,1020.040000,1.000000,23.600000,67.500000,19.770000
50%,25285.500000,5.790000,1234.650000,1.000000,24.400000,71.700000,21.520000
75%,37927.750000,6.680000,1329.067500,2.000000,25.100000,77.500000,23.277500
max,50570.000000,11.570000,2278.350000,3.000000,70.000000,3312.600000,25.000000

#### Exploratory Data Prep and Cleaning

In [17]:
# fill the missing values with the most frequent state(mode)

df['add_water']=df['add_water'].fillna(df['add_water'].mode()[0])

In [18]:
# drop redundant ID column 

df = df.drop(columns=['id'])

In [19]:
df.columns

Index(['timestamp', 'pH', 'TDS', 'water_level', 'DHT_temp', 'DHT_humidity',
       'water_temp', 'pH_reducer', 'add_water', 'nutrients_adder',
       'humidifier', 'ex_fan'],
      dtype='str')